### ISSUE TITLE
Issue-test: add tests

### ISSUE THREAD

**Issue by angel-1x** [angel-1x/zshhhh#22]
Automated Review Comments
Issues in yarn-deps/package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
Issues in yarn-deps/src/main.rs:
  - (8, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (67, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
Issues in yarn-scripts/package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in yarn-scripts/src/main.rs:
  - (8, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')

**Comment by drone-1x** [comment]
I got it.
