### ISSUE TITLE
Issue-style: reformat code

### ISSUE THREAD

**Issue by angel-1x** [angel-1x/zshhhh#40]
Automated Review Comments
Issues in yarn-deps/src/main.rs:
  - (36, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (84, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
Issues in yarn-scripts/src/main.rs:
  - (40, 'Line exceeds 80 characters')

**Comment by doraemon-35** [comment]
I got it.
